#!/bin/bash

# Get local configuration
source ~/.webbackup

if [[ ${#WEBPATHS[@]} -lt 1 ]]; then
    echo >&2 "You must specify at least one path to backup!"
    exit 1
fi

if [[ -z "$BUCKET" ]]; then
    echo >&2 "You must specify an s3 bucket for uploading!"
    exit 1
fi
