#!/bin/bash

# webbackup: backup upload directories to AWS s3
# Copyright (C) 2015 Mario Finelli
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Get local configuration
source ~/.webbackup

if [[ ${#WEBPATHS[@]} -lt 1 ]]; then
    echo >&2 "You must specify at least one path to backup!"
    exit 1
fi

if [[ ${#WEBPATHS[@]} -ne ${#PREFIX[@]} ]]; then
    echo >&2 "You don't have prefixes to match paths!"
    exit 1
fi

if [[ -z "$BUCKET" ]]; then
    echo >&2 "You must specify an s3 bucket for uploading!"
    exit 1
fi

command -v s3cmd >/dev/null 2>&1 || { \
    echo >&2 "S3cmd is not installed. Aborting!"; exit 1; \
}

# Make sure that s3cmd has been configured
if [ ! -f ~/.s3cfg ]; then
    echo >&2 "S3cmd has not been configured yet. Aborting!"
    exit 2
fi

for i in "${!WEBPATHS[@]}"; do
    # Make sure path ends in a "/"
    case "${WEBPATHS[$i]}" in
        */)
            webpath="${WEBPATHS[$i]}"
            ;;
        *)
            webpath="${WEBPATHS[$i]}/"
            ;;
    esac

    echo "Backing up path: ${webpath}"

    s3cmd sync --delete-removed \
        --exclude '.gitignore' \
        --acl-private \
        --guess-mime-type \
        --server-side-encryption \
        "$webpath" s3://"$BUCKET"/"${PREFIX[$i]}/"
done
